- hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - name: docker build
      command: "docker build -t {{ image_name }}:{{ tag }} ."

    # image should be push into a private registry
    # - name: docker push
    #   command: "docker push {{ image_name }}:{{ item }}"
    #   with_items: "{{ tags }}"
